# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Astro-Telescope
version:      0.60
version_from: Telescope.pm
installdirs:  site
requires:
    Astro::SLA:                    0.93

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
